apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
  labels:
    app: deployment-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-backend-replica
  template:
    metadata:
      labels:
        app: api-backend-replica
    spec:
      containers:
      - name: api-backend-kuber
        image: api-backend:v1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: my-api-backend-service
spec:
  type: NodePort
  selector:
    app: api-backend-replica
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30100